### ISSUE TITLE
[BUG] Doing /axh vault throws console error

### ISSUE THREAD

**Issue by ChiboYen** [Mangonels/AntiXrayHeuristicsIssues#22]
**Server system:** [Spigot/Paper] Paper

**Minecraft version:**
1.16.5

**Steps to reproduce the issue:**
Use the /axh vault command

**Error log:**
```
[17:52:43 INFO]: ChiboYen issued server command: /axh vault
[17:52:43 WARN]: [AntiXrayHeuristics] Plugin AntiXrayHeuristics v1.3.8 generated an exception while executing task 15142268
java.lang.NullPointerException: null
        at es.mithrandircraft.antixrayheuristics.MemoryManager.GetAllBaseXrayerData(MemoryManager.java:115) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.XrayerVault.lambda$UpdateXrayerInfoLists$3(XrayerVault.java:154) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1059]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1059]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1059]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Link to config.yml file on gist.github.com:** Unmodified

**Comment by ChiboYen** [comment]
This is rather a now urgent issue, AXH is not working on my server entirely. It does not detect xrayers, and leaves my server exposed to xraying.

```
[02:44:30 INFO]:        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:5[OverwatchAXR] Fanta_Doge was automatically detected for x-raying
[02:44:30 WARN]: [AntiXrayHeuristics] Plugin AntiXrayHeuristics v1.3.8 generated an exception while executing task 19071478
java.lang.NullPointerException: null
        at es.mithrandircraft.antixrayheuristics.MemoryManager.StorePlayerData(MemoryManager.java:56) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.XrayerHandler.lambda$HandleXrayer$0(XrayerHandler.java:48) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1059]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1059]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1059]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
```

**Comment by Mangonels** [comment]
Hey, apologies for the delay in answering.

I've been too busy with my work, and ironically, also spend all my free time developing AXH (recently). I've been focusing on making it work on all versions.

So, now I finally got the moment to look at your particular issue: I've currently done a quick test on a clean 1.16.5 Paper server, and everything seems to work fine. This may have something to do with the considerable amount of internal changes I've made to the plugin, but the fact is that, right now, I cannot reproduce what you say

As for "AXH is not working on my server entirely. It does not detect xrayers, and leaves my server exposed to xraying." I'll do some testing right now to check it's even working.

I hope this message gives you at least some tranquility that I am working on it, even though I could barely track this issue.

Any further details are welcome, also, please try installing this on a clean server, and switching (just in case it's somehow something particular with the persistant storage method on 1.16.5, although I wouldn't see why).

**Comment by ChiboYen** [comment]
This has left my server exposed wide open to x-rayers, please do look into it further or if you can send me your development version that would be appreciated as well.
This exception occurs when an xrayer is detected, my files are all yml validated and there are no other errors
```
axh xrayer ChiboYen
[20:01:50 INFO]: [OverwatchAXR] ChiboYen was automatically detected for x-raying
[20:01:50 WARN]: [AntiXrayHeuristics] Plugin AntiXrayHeuristics v1.3.8 generated an exception while executing task 27647168
java.lang.NullPointerException: null
        at es.mithrandircraft.antixrayheuristics.MemoryManager.JSONPlayerDataStore(MemoryManager.java:550) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.MemoryManager.StorePlayerData(MemoryManager.java:63) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.XrayerHandler.lambda$HandleXrayer$0(XrayerHandler.java:48) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1059]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1059]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1059]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Mangonels** [comment]
Try the latest version.

**Comment by Mangonels** [comment]
I will asume this matter is solved, feel free to re-open if there are still any issues.
