### ISSUE TITLE
[BUG] NullPointerException on startup when using MySQL

### ISSUE THREAD

**Issue by RalphORama** [Mangonels/AntiXrayHeuristicsIssues#23]
**Server system:** Paper (`git-Paper-602`)
**Minecraft version:** 1.16.5
**System info:**

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
:/home/container$ java -Xms7168M -Xmx7168M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dterminal.jline=false -Dterminal.ansi=true -jar papermc.jar
System Info: Java 11 (OpenJDK 64-Bit Server VM 11.0.10+9) Host: Linux 4.15.0-141-generic (amd64)
```

**Steps to reproduce the issue:** 
1. Install plugin
2. Set up MySQL (see linked config file)
3. Restart server
4. Error appears

**Error log:**

```log
[09:15:34 WARN]: [AntiXrayHeuristics] Plugin AntiXrayHeuristics v1.3.8 generated an exception while executing task 551
java.lang.NullPointerException: null
        at es.mithrandircraft.antixrayheuristics.MemoryManager.SQLCreateTableIfNotExists(MemoryManager.java:283) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.AntiXrayHeuristics.lambda$onEnable$0(AntiXrayHeuristics.java:115) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-607]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-607]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-607]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Link to config.yml file:** https://pastebin.com/SZvapx7n

**Comment by Mangonels** [comment]
JSON seems fine at first glance. Stick to that, it's just as good.
