### ISSUE TITLE
1.3.9 (1.12.2) Vault Bug

### ISSUE THREAD

**Issue by MythricHD** [Mangonels/AntiXrayHeuristicsIssues#24]
Server system: Paper Spigot

Minecraft version:
1.12.2

Plugin version:
1.3.9

Steps to reproduce the issue:
 /axh vault command not opening gui due to invalid item id

**Config is all default**

Error log:
```[21:39:54 WARN]: [AntiXrayHeuristics] Plugin AntiXrayHeuristics v1.3.9 generated an exception while executing task 87313
java.lang.NoSuchFieldError: PLAYER_HEAD
        at es.mithrandircraft.antixrayheuristics.HeadManager.GetHead(HeadManager.java:44) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.HeadManager.GetPlayerHead(HeadManager.java:35) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.XrayerVault.UpdateXrayerHeadCache(XrayerVault.java:322) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.XrayerVault.lambda$OpenVault$4(XrayerVault.java:239) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(:64) ~[paper-1.12.2.jar:git-Paper-368202a]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(:52) ~[paper-1.12.2.jar:git-Paper-368202a]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(:22) ~[paper-1.12.2.jar:git-Paper-368202a]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by Mangonels** [comment]
Disable playerheads in config.

Installation instructions have changed.
