### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Weark** [Mangonels/AntiXrayHeuristicsIssues#28]
**Server system:** Purpur
**Minecraft version:** 1.16.5
**Steps to reproduce the issue:** 
Sometimes the command: '/ antixrayheuristics vault' stops working.
**Error log:**
[03:29:54 INFO]: Weark issued server command: /antixrayheuristics vault
[03:29:54 WARN]: [AntiXrayHeuristics] Task #21170002 for AntiXrayHeuristics v1.3.10 generated an exception
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.XrayerVault.ConstructVault(XrayerVault.java:273) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.XrayerVault.OpenVault(XrayerVault.java:239) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.XrayerVault$1.onQueryDone(XrayerVault.java:185) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.MemoryManager$9.run(MemoryManager.java:641) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1144]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:451) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1144]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Link to config.yml file on gist.github.com:**
https://gist.github.com/Weark/31ac1818ebf5384379bead586f9dd56e

**Comment by Mangonels** [comment]
UseHeadsInGUI: false
There are a few warnings about this on the changelog.
