### ISSUE TITLE
[BUG] Error while processing...

### ISSUE THREAD

**Issue by Brancast** [Mangonels/AntiXrayHeuristicsIssues#32]
**Server system: Paper
**Minecraft version: 1.16.5

**Error log:
§5[§bAntiXrayHeuristics§5] §aKofluk §bwas automatically registered and handled for xraying.
Plugin AntiXrayHeuristics v1.3.10 generated an exception while executing task 315643
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.storedXrayersFromJSON" is null
	at es.mithrandircraft.antixrayheuristics.MemoryManager.JSONPlayerDataStore(MemoryManager.java:551) ~[?:?]
	at es.mithrandircraft.antixrayheuristics.MemoryManager.StorePlayerData(MemoryManager.java:63) ~[?:?]
	at es.mithrandircraft.antixrayheuristics.XrayerHandler.lambda$HandleXrayer$0(XrayerHandler.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-788]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-788]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

Link to config.yml file on gist.github.com: I didn't make any changes

**Comment by Mangonels** [comment]
If JSON storage method systematically doesn't work (like from a clean installation it doesn't work, or eventually it stops working), your only option for now is to use SQL instead.

I'll take a look at this once I resume development of AXH. Even if JSON works fine on a clean installation, this error shouldn't occur.

**Comment by Brancast** [comment]
"If JSON storage method systematically doesn't work" probably a problem with server ram. Also thank you <3

**Comment by Mangonels** [comment]
If your server has a good amount of free ram, and your json file isn't too large (Like, the vault isn't more than 1 page long), you shouldn't blame your ram.

I did however think at first this could have something to do with a loading problem caused by some system limit, but I wouldn't confirm it.

**Comment by Brancast** [comment]
ok thank you <3
