### ISSUE TITLE
[BUG] /cmi anvil causing exception with AXH

### ISSUE THREAD

**Issue by mrfloris** [Mangonels/AntiXrayHeuristicsIssues#4]
**Server system:** Spigot
**Minecraft version:** 1.15.1
**Steps to reproduce the issue:** Type /cmi anvil
**Error log:**
```
[06:09:20] [Server thread/INFO]: Tidala issued server command: /anvil
[06:09:21] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to AntiXrayHeuristics v1.3.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1250) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1926) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Title not set
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.Container.getTitle(Container.java:48) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at es.mithrandircraft.antixrayheuristics.events.InventoryCloseEv.closeEv(InventoryCloseEv.java:24) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor641.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        ... 18 more
```

CMI is a premium plugin, after my report on the forums there's an update with a changelog entry how /cmi anvil (a new command they added this month) had a tiny update to fix issue breaking on other plugins. 

Reporting this anyway, in case it was unrelated to plugins like these. We're in the middle of an event and cant test/restart the servers right now to double triple check.

/cmi anvil is a command that lets you edit where you stand as if you right clicked on an anvil. 
Kinda like /furnace opens a furnace, or /workbench a crafting table or /enderchest opens your enderchest. 

Sorry that i dont have further information on this. If we update wednesday afternoon to newer builds and the issue went away i will report back here.

**Comment by Mangonels** [comment]
I'll be expecting a confirmation on if this still occurs even after updating cmi, in order to consider working on this issue on my side.

Still intrigued on why it could cause an internal error inside my own plugin, but if they can fix it, it's fine by me.

**Comment by mrfloris** [comment]
I had a little bit of time, before my crazy week starts. 

I've made sure I am on the latest AXH and CMI, and i can no longer reproduce the issue. 

So for me, this has been resolved.
