### ISSUE TITLE
[BUG] Plugin won't start on 1.12

### ISSUE THREAD

**Issue by Souvlakis** [Mangonels/AntiXrayHeuristicsIssues#8]
**Server system:** Paper 1.12.2
**Minecraft version:** 1.12.2
**Error log:**
`[13:14:24 ERROR]: Error occurred while enabling AntiXrayHeuristics v1.3.7 (Is it up to date?)
java.lang.NoSuchFieldError: GRAY_STAINED_GLASS_PANE
        at es.mithrandircraft.antixrayheuristics.gui.XrayerVault.<init>(XrayerVault.java:52) ~[?:?]
        at es.mithrandircraft.antixrayheuristics.AntiXrayHeuristics.onEnable(AntiXrayHeuristics.java:83) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1613]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1613]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1613]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1613]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1613]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]`
**Link to config.yml file on gist.github.com:** I am using the default config

**Comment by Mangonels** [comment]
Are you using the 1.9+ API jar?

**Comment by Mangonels** [comment]
Asuming you weren't. Reopen if there's any further issues.
